--- !ditz.rubyforge.org,2008-03-06/project 
name: cymple
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: cymple
- !ditz.rubyforge.org,2008-03-06/component 
  name: data
- !ditz.rubyforge.org,2008-03-06/component 
  name: toolkit
- !ditz.rubyforge.org,2008-03-06/component 
  name: app
- !ditz.rubyforge.org,2008-03-06/component 
  name: docs
releases: []

